version: '2'

services:
    ethernode0:
      container_name: ethernode0
      hostname: ethernode0
      extends:
         file: compose-defaults.yml
         service: ethernode 
      ports:
         - "8545:8545"
      networks:
         - ether-net0

    ethernode1:
      container_name: ethernode1
      hostname: ethernode1
      extends:
         file: compose-defaults.yml
         service: ethernode 
      networks:
         - ether-net0

    ethernode2:
      container_name: ethernode2
      hostname: ethernode2
      extends:
         file: compose-defaults.yml
         service: ethernode 
      networks:
         - ether-net0

    ethernode3:
      container_name: ethernode3
      hostname: ethernode3
      extends:
         file: compose-defaults.yml
         service: ethernode 
      networks:
         - ether-net0

    ethermgmt:
      container_name: ethermgmt
      hostname: ethermgmt
      extends:
         file: compose-defaults.yml
         service: ethermgmt 
      command: sh -c 'sleep 10 && /bootstrap.sh ethernode1 ethernode0 && /bootstrap.sh ethernode2 ethernode0 && /bootstrap.sh ethernode3 ethernode0 && /bootstrap.sh ethernode1 ethernode2 && /bootstrap.sh ethernode1 ethernode3 && /bootstrap.sh ethernode2 ethernode3 && nginx && cd /root/eth-net-intelligence-api/ && pm2 start app.json && cd /root/eth-netstats && npm start'
      tty: true
      ports:
         - "3000:3000"
         - "3001:3001"
      links:
         - ethernode0
         - ethernode1
         - ethernode2
         - ethernode3
      networks:
         - ether-net0

networks:
   ether-net0:
     driver: bridge
     ipam:
        driver: default
        config:
           - subnet: 10.1.1.0/24
             ip_range: 10.1.1.128/28
             gateway: 10.1.1.1
